### ISSUE TITLE
SpringCloud教程第12篇：Hystrix Dashboard（F版本） - 方志朋的博客

### ISSUE THREAD

**Issue by forezp** [miles02/blog-comments#18]
https://www.fangzhipeng.com/springcloud/2018/08/30/sc-f12-dash/ 

 方志朋的博客

**Comment by weijingwei** [comment]
好像少了一些配置信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

**Comment by SuperChrisliu** [comment]
使用`@SpringCloudApplication`代替
```
@SpringBootApplication
@EnableDiscoveryClient
@EnableCircuitBreaker
```
springboot2.0.8需要增加配置：
```
management:
  endpoints:
    web:
      exposure:
        include: '*'
```
